const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `They are made from thinner batter than actual cakes, and a little hot grease sets the outer surface quickly; this allows the inside to remain fluffy and light.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Two ¼ pound patties on a potato roll with house pickles, spinach, tomatoes, American cheese, onion, and special sauce. `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Milo blended with banana & mint chocolate chip ice cream, drizzled with melted chocolate & topped with more ice cream & Milo.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `A properly cooked half fry will be opaque and perfectly set, nestling a soft yolk in the center. A single poke will have the yolk oozing out. Buttered toast dipped in runny yolk offers a unique mix of flavours! `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: ` The Egg Attack features a fried egg, thickly-cut bacon and cheddar cheese smothered over their famous single or double all-beef patties. `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Oreo and vanilla milkshake is blended together while it is topped with Dream Oreo Cheesecake and Hot Fudge. `,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Bacon-wrapped foods are foods that are prepared by being covered in bacon. They may be baked, fried, or grilled. `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Burger · Pancakes · Egg McMuffin · Cheeseburger · Garden Salad · Rainbow Fruit Kabobs · Deviled Eggs · Crispy Smashed Potatoes fries `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `4 scoops vanilla ice cream ; 2 scoops chocolate ice cream ; 3/4 cup whole milk ; 1/3 cup caramel syrup ; Sea salt for topping. `,
  },
];
export default menu;
